module.exports = {
	"CNBC": "msm", 
	"Bloomberg": "msm", 
	"Nasdaq": "msm", 
	"Inc.com": "msm", 
	"EconoTimes": "msm", 
	"Fortune": "msm", 
	"Yahoo Finance": "msm", 
	"Business Insider": "msm",
	"Forbes": "msm",
	"Financial Times": "msm",
	"The Economist": "msm",
	"The Verge": "msm",
	"PR Newswire (press release)‎": "msm",
	"Investopedia‎": "msm",
	"Mic": "msm",
	"TechCrunch": "tech",
	"Futurism": "tech",
	"Motherboard": "tech",
	"VentureBeat": "tech",
	"CoinTelegraph": "crypto",
	"The Merkle": "crypto",
	"newsBTC": "crypto",
	"Inside Bitcoins": "crypto",
	"Coinspeaker": "crypto",
	"CoinDesk": "crypto",
	"ETHNews": "crypto",
	"CryptoCoinsNews": "crypto", 
	"CryptoNinjas‎": "crypto", 
	"Bitcoin Magazine‎": "crypto"
}
